#!/usr/bin/env python

# Title: Personal Site Emailing
# Description: Sending mail from my personal site using Selenium Webdriver
# Author: William Chanrico
# Date: 14-Dec-2016

import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

print(" _____________________ 	")
print("/ hello, who's there? \\	")
print("\\ william said hi...  /	")
print(" ---------------------	")
print("       \\   ,__,			")
print("        \\  (..)____		")
print("           (__)    )\	")
print("              ||--|| *	")

driver = webdriver.Firefox()

driver.get('http://localhost/arzhonid/')

assert 'Arzhon - William Chanrico' in driver.title

# driver.implicitly_wait(10)

driver.find_element_by_xpath(".//*[@id='main']/footer/ul[2]/li[1]/a").click()

WebDriverWait(driver, 10).until(
    EC.presence_of_element_located((By.XPATH, ".//*[@id='name']"))
)

driver.find_element_by_xpath(".//*[@id='four-link']").click()
driver.find_element_by_xpath(".//*[@id='name']").send_keys("this is name")
driver.find_element_by_xpath(".//*[@id='subject']").send_keys("typing on subject")
driver.find_element_by_xpath(".//*[@id='email']").send_keys("test@test.com")
driver.find_element_by_xpath(".//*[@id='message']").send_keys("DELAYING 3 SECONDS before submit")

time.sleep(3)

driver.find_element_by_xpath(".//*[@id='four']/div/form/div[4]/div/ul/li[1]/input").click()

